      - name: Build APK
        run: |
          flet build apk --org com.ghasab --product downloader --android-permissions "android.permission.INTERNET,android.permission.WRITE_EXTERNAL_STORAGE,android.permission.READ_EXTERNAL_STORAGE,android.permission.MANAGE_EXTERNAL_STORAGE"
